### ISSUE TITLE
Inquiry on wiki_prop.py

### ISSUE THREAD

**Issue by tonytan48** [SasCezar/XWikiRE#1]
Hi Cezar,

    This is Tan Qingyu, a PhD student from National University of Singapore. Thank you for your great work. We are very interested in the X-Wiki-RE tool and we are trying to build some distantly supervised data for our own. Also, we are interested in cross-lingual relation extraction. However, we have some question in using X-Wiki-RE: 
    1) The dataset link in https://github.com/google-research-datasets/wiki-reading is empty. We tried to contact the authors of WikiReading but haven't got back from them. May I know where can we access the processed data of English, German, French, Spanish and Italian?
    2) We tried to process some Chinese data using X-Wiki-RE and wiki_prop.py at https://github.com/SasCezar/XWikiRE/commit/bbdcc8d2caba6bfb90fe951a2d154a9d494e3b2e. But the default encoding 'ANSI' is not recognizable. We tried several encodings but still found 0 mappings. May I know what is the possible cause for this?

    Thanks again for your time and hope to hear from you.

Best regards,
Qingyu

**Comment by SasCezar** [comment]
The overall process was intended to be like this: 
          - Take the Wikipedia dump, load into the Mongo DB and index it; (ideally JSON)
          - Take the Wikidata dump, load into the Mongo DB and index it; (Ideally JSON)
          - Combine their information, and save the new combined data in a DB, and index it.
          - Use the previous combined information in any way you want (we used it for both WikiReading, and a custom Semantic Role Labelling dataset).

Regarding:
1 - Are you referring to the fact that the link is broken? I can't help you with that, as I don't have a backup. I can see that you are not alone, on GitHub there is already an issue, so I guess the data is gone. 
2 - The code should be reproducible as I reused it in 2019, however, I think I made a bit of a mess at some point with the README file, I'm sorry, I think is best if you use this version: https://github.com/SasCezar/XWikiRE/tree/naacl.  However, if you use the JSON dump, this should not be required if I recall correctly. 
3 - Same as for 2, if you use the JSON dump, this should not be required if I recall.
